Added default value for setPostCode in CustomerAddressInterface and C…
emartech/magento2-extension pull request #31
Opened 2023-01-17 15:21 UTC by lucacanella

…ustomerAddress to prevent error when handleAddressWebsiteData returns null for 'postcode'.

Tested only on a specific instance, where a null postcode was returned here: https://github.com/emartech/magento2-extension/blob/570f7288daadee6c5008e705a0121e4fe07a32b7/Helper/Customer.php#L691

2023-01-18 08:25 UTC, ptomi requested changes
Thank you very much for your pull request!

This is not enough and not good enough. If we allow the postcode to be null in the setter, then the getter can also have a null return value

2023-01-18 13:39 UTC, lucacanella commented
> Thank you very much for your pull request!
> 
> This is not enough and not good enough. If we allow the postcode to be null in the setter, then the getter can also have a null return value

You're right, I added the nullable type in the getters (comments included). Let me know if this is ok.

2023-01-19 11:28 UTC, lucacanella reviewed
Added nullable return type in next commit.

2023-01-23 08:34 UTC, ptomi approved these changes

2023-01-23 09:12 UTC, merged